### ISSUE TITLE
Dataset README & empty "query", "answer" values

### ISSUE THREAD

**Issue by dhkim16** [niansong1996/lever#3]
Hi there, thanks for the interesting work.

I was specifically looking into WikiTableQuestions of the released dataset and found it somewhat cryptic.
My best guess is that the `generated_programs` is referring to the multiple candidate executions, `generated_program` is the one selected by the algorithm, `gold_program` is the oracle.
I assume I should be looking into the `exec_results` to see the answer.

Then, in the `metadata`, I see both `answer` and `original answer`. I assume `original answer` refers to the answer given in the original work (i.e., the gold answers) and that the `answer` is the answer generated by your system.
However, the issue here is that `answer` seems to be just empty string many of the cases -- this is true for the dev set, and especially true for the test set (for which almost everything appears empty).

It is true that I might be just misunderstanding the data structure and believe that a README for the dataset would greatly help. Would you mind generating a README for the dataset and checking whether my understanding of the data is correct? If it is correct, would you mind looking into the `answer` (and `query`) fields that seem to be just blank most of the time?

Thanks in advance!

**Comment by drproduck** [comment]
@dhkim16 after computing the metrics myself and comparing with the paper, I'm pretty sure that generated_program is the greedy decoding output. I'm looking for answers to the other questions @niansong1996

**Comment by niansong1996** [comment]
Hi @dhkim16 sorry for the (super) late reply, to answer your questions:

1. The `generated_programs` field is obtained by sampling and `generated_program` is by greedy decoding as @drproduck mentioned, sorry for the confusing names 😅 
2. `gold_program` is the oracle but for WikiTableQuestions, it does not come with gold programs, so we use the annotated programs in [squall](https://github.com/tzshi/squall). And `answer` is the execution results of those annotation programs. 
3. However since not all the WikiTQ questions have a SQL solution, many of them are empty for the dev set, and test sets are not annotated in squall. But this part is rather irrelevant as we did not use the `gold_program` or `answer` field for any of the evaluation pipeline, we use the `original_answer` and the original script for evaluating WikiTQ for producing the numbers in the paper.
4. That being said, we did use the nicely converted tables from squall, since the original table of WikiTQ is very noisy. So we ask the model to generate SQLs and execute on the processed tables in squall.

Let me know if you have any follow-up questions!

**Comment by drproduck** [comment]
hi @niansong1996 ,

I'm currently using your code and datasets for fine-tuning the Spider and WikiTQ models, and I have a few questions regarding the 'example_to_demonstration_sql' function in the 'spider_reader.py' file. I noticed that there are two versions of this function, one with '_bridge' and one without it, and I'd like to understand the purpose of the 'bridge' version and how it relates to including the schema.

Additionally, I encountered an issue related to a missing file, specifically '../../../data/squall/db_info_wtq.json.' Could you please direct me to where I can find or obtain this file? 

Your guidance and clarification on these matters would be incredibly valuable to me!

**Comment by niansong1996** [comment]
Hi @drproduck ,

Very sorry for the late reply. Yes, I realized that I didn't include `db_info_wtq.json` which is essential to run experiments for WikiTableQuestions.

I'm uploading it here for now (and will update instructions on the README later):
[db_info_wtq.json](https://github.com/niansong1996/lever/files/13631159/db_info_wtq.json)

**Comment by niansong1996** [comment]
Closing this issue for now but feel free to re-open if you have further questions.
